[package]
name = "wozard"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features = ["debug", "bevy_dev_tools"] }
bevy_pancam = "0.19.0"
noise = "0.9.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
